### PR TITLE
Implement CSS grid, fix layout bugs

### LINKED ISSUE #172: When changing screen widths *after* the app has loaded, the sidebar does not responsively collapse/expand
Here's a GIF of it happening via the inspector, but __this is reproducible on mobile too__ when switching from portrait to landscape, which is the main concern!

screen recording 2018-08-29 at 01 08 pm

### PR DESCRIPTION
**Pull request by radotreyes**
Starting to implement CSS grid throughout the whole application, starting with `App.js` and all its first-level children. Will extend this to all children of the main content div.

Also fixed #172 and added Twitter-style sidebar behavior on mobile.

Hoping to continue to refactor in this style to make way for an easier redesign.

### CODE REVIEW

File: src/App.js [hunk 1]
```diff
@@ -46,78 +95,63 @@ class App extends Component {
...
     this.setState({
-      shouldShowSidebar: !shouldShowSidebar,
+      isNarrowScreen: window.innerHeight > window.innerWidth,
     });
   }
 
-  handleCloseClick(event) {
+  handleSidebarToggle(event) {
     const { shouldShowSidebar } = this.state;
+    console.log('ouch');
```
Comment (austintackaberry) [inline src/App.js]: Should probably remove this console.log

**Comment by radotreyes** [comment]
I agree with you, and I was worried I would introduce some bugs. Fortunately `cursor: pointer` is an easy fix.

* The animations run too long and I picked a weird `cubic-bezier`! Will mess with that more to smooth it out.
* I did actually implement a dark overlay and disabled interaction with the main content when the sidebar is expanded on mobile. However, I commented it out of the commits that I pushed because I was seeing some performance issues. 
   * Might have something to do with the `transition-timing-function` (cubic-bezier) I picked for the animation?
   * Not sure why this is happening as I'm using a `:before` selector and "no JavaScript" (it's styled components, so it's JavaScript lol) to do this... so I wanted to take a further look. 
* I do also think that clicking/tapping on main content to close the sidebar would be good!
* I agree with making the collapsed sidebar transparent and leaving only the hamburger. However, and I just thought of this, we could maybe use an opaque sidebar space to contain some minimized versions of the modules that we have/will have in the expanded sidebar? This is probably an issue for a separate PR though. Making it transparent won't be a problem for now.
